version: "3.9"
services:
  app:
    build: .
    environment:
      - SYMBOL=BTCUSDT
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8050:8050"
